name: release-please

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{secrets.GITHUB_TOKEN}}

            # Output which releases were created
            - name: Output release info
              run: |
                  echo "releases_created:" ${{ steps.release.outputs.releases_created }}
                  echo "released paths:" ${{ steps.release.outputs.paths_released }}

            # Check to see if we need to do any releases and if so check out the repo
            - uses: actions/checkout@v4
              if: ${{ steps.release.outputs.releases_created == 'true' }}

            # we can do this because deno is smart enough to skip packages if they are already up to date
            - name: Attempt to publish packages
              run: |
                  npx jsr publish
              if: ${{ steps.release.outputs.releases_created == 'true' }}
