name: Comment New Releases

on:
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    comment:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'github-actions[bot]' }}
        permissions:
            pull-requests: write

        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{secrets.GITHUB_TOKEN}}
                  # make sure we don't unintentionally create a release
                  skip-github-pull-request: true
                  skip-github-release: true

            - uses: actions/checkout@v4
              if: ${{ steps.release.outputs.releases_created == 'true' }}
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.head_ref }}

            - name: Comment no releases
              if: steps.release.outputs.releases_created == 'false'
              uses: mshick/add-pr-comment@v2
              with:
                  message: |
                      :warning: No releases will be generated by this PR
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  allow-repeats: false

            - name: Comment releases
              if: steps.release.outputs.releases_created == 'true'
              uses: mshick/add-pr-comment@v2
              with:
                  message: |
                      ${{ steps.release.outputs.paths_released }}
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  allow-repeats: false
