name: Version Bump

on:
    push:
        branches:
            - main

jobs:
    build:
        name: version bump
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Set up Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: canary

            - name: Run workspaces version bump
              run: |
                  git fetch --unshallow origin
                  deno run -A jsr:@deno/bump-workspaces@0.1.21/cli
              env:
                  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
